# --- Atualização do Dicionário INFO_RADIOS para o app.py ---

INFO_RADIOS = {
    'Portátil - MTP3500': {
        'nome': 'MTP3500 TETRA',
        'tipo': 'Portátil',
        'compatibilidade_acessorio': 'MTP3000',
        'frequencia': '350 - 470 MHz',
        'teclado': 'Teclado Simplificado (LKP - Limited Keypad)',
        'protecao': 'IP65 / IP67 (Resistente à água e poeira)',
        'resumo': 'Rádio portátil de missão crítica construído para alta durabilidade. Oferece clareza de áudio excepcional e operação intuitiva em ambientes severos.',
        'antena': 'Inclusa (Antena Whip 110mm / 380-430MHz)',
        'criptografia': 'TEA1 (Criptografia de Interface Aérea)',
        'bateria_padrão': 'Bateria Padrão Li-Ion 2200 mAh inclusa no kit base',
        'gps': 'Possui licença GPS ativada',
        'bluetooth': 'Bluetooth Smart Ready / Áudio sem fio',
        'potencia': 'Suporta Licença TOGGLE RF POWER CLASS 3 (Aumento de potência para 2.8W)',
        'mandown': 'Suporta Licença Man Down (Alarme/Sensor automático de queda do operador)'
    },
    'Portátil - MTP3550': {
        'nome': 'MTP3550 TETRA',
        'tipo': 'Portátil',
        'compatibilidade_acessorio': 'MTP3000',
        'frequencia': '350 - 470 MHz',
        'teclado': 'Teclado Alfanumérico Completo (FKP - Full Keypad)',
        'protecao': 'IP65 / IP67',
        'resumo': 'Versão com teclado completo alfanumérico e display colorido. Permite envio e recebimento rápido de mensagens de texto, chamadas privadas e navegação completa por menus.',
        'antena': 'Inclusa (Antena Whip 110mm / 380-430MHz)',
        'criptografia': 'TEA1 (Criptografia de Interface Aérea)',
        'bateria_padrão': 'Bateria Padrão Li-Ion 2200 mAh inclusa',
        'gps': 'GPS Integrado com Licença Ativa',
        'bluetooth': 'Bluetooth Smart Ready & Localização Indoor',
        'potencia': 'Suporta Licença TOGGLE RF POWER CLASS 3 (Aumento de potência para 2.8W)',
        'mandown': 'Suporta Licença Man Down (Sensor de homem caído e imobilidade)'
    },
    'Portátil - MXP600': {
        'nome': 'MXP600 TETRA',
        'tipo': 'Portátil Avançado',
        'compatibilidade_acessorio': 'MXP600/MXP660',
        'frequencia': '350 - 470 MHz',
        'teclado': 'Teclado Completo HD',
        'protecao': 'IP68 (Submersível até 2m por 2h)',
        'resumo': 'O terminal portátil TETRA mais leve e moderno do mercado. Possui supressão de ruído com Inteligência Artificial, Wi-Fi 2.4/5GHz e HD Audio.',
        'antena': 'Inclusa (Antena Whip UHF 380-470MHz)',
        'criptografia': 'TEA1 e End-to-End Encryption (E2EE) ready',
        'bateria_padrão': 'Bateria IMPRES 2 Li-Ion IP68 alta capacidade',
        'gps': 'Multi-GNSS (GPS, GLONASS, BEIDOU, GALILEO)',
        'bluetooth': 'Bluetooth 5.0 com localização indoor acelerada',
        'potencia': 'RF Class 3 (2.8W) estendido',
        'mandown': 'Man Down integrado com sensores de acelerômetro de última geração'
    },
    'Portátil - MTP8550EX - 380MHz': {
        'nome': 'MTP8550EX TETRA ATEX',
        'tipo': 'Portátil Intrinsecamente Seguro',
        'compatibilidade_acessorio': 'MTP8550EX',
        'frequencia': '380 - 430 MHz',
        'teclado': 'Teclado Completo (Projetado para uso com luvas pesadas)',
        'protecao': 'IP66 / IP67 & Certificação ATEX / IECEx Zona 1 e 21',
        'resumo': 'Projetado para atmosferas explosivas em indústrias químicas, refinarias e plataformas de petróleo. Formato em "T" ergonômico e display superior secundário.',
        'antena': 'Inclusa (Antena Whip ATEX 350-470MHz)',
        'criptografia': 'TEA1 Hardware Encryption',
        'bateria_padrão': 'Bateria IMPRES Li-Ion ATEX IP67 dedicada inclusa',
        'gps': 'GNSS Integrado',
        'bluetooth': 'Bluetooth ATEX seguro',
        'potencia': 'Potência otimizada para segurança intrínseca ATEX',
        'mandown': 'Sensor Man Down avançado de fábrica'
    },
    'Móvel - MXM600': {
        'nome': 'MXM600 TETRA',
        'tipo': 'Móvel / Veicular / Fixo',
        'compatibilidade_acessorio': 'MXM600',
        'frequencia': '350 - 470 MHz',
        'teclado': 'Cabeçote de Controle Inteligente',
        'protecao': 'IP54 / Mil-Std 810G',
        'resumo': 'Terminal veicular/fixo TETRA de alta potência operacional. Ideal para instalação em viaturas, ambulâncias, embarcações e salas de controle.',
        'antena': 'Conexão para Antena Veicular externa de alto ganho',
        'criptografia': 'TEA1 Criptografia de canal',
        'bateria_padrão': 'Alimentação via bateria do veículo / Fonte externa 12V',
        'gps': 'GPS/GNSS com suporte a antenas veiculares',
        'bluetooth': 'Bluetooth 5.0 integrado',
        'potencia': 'Potência nativa de rádio móvel veicular',
        'mandown': 'Não aplicável a rádios móveis (Emergência via botão/pedal externo)'
    }
}